build_test_get_nibble: 
	gcc -Wall -o test_get_nibble.exe problem1.c testsProblem1/test_get_nibble.c

test_get_nibble: build_test_get_nibble
	./test_get_nibble.exe

build_test_rotate_halves: 
	gcc -Wall -o test_rotate_halves.exe problem1.c testsProblem1/test_rotate_halves.c

test_rotate_halves: build_test_rotate_halves
	./test_rotate_halves.exe

build_test_set_nibble: 
	gcc -Wall -o test_set_nibble.exe problem1.c testsProblem1/test_set_nibble.c

test_set_nibble: build_test_set_nibble
	./test_set_nibble.exe